version: '3'

networks:
  traefik:
    external: true
  pgsql:
    external: true

volumes:
  pgsql:

services:
  traefik:
    image: traefik:latest
    container_name: "traefik"
    command:
      - "--pilot.token=${PILOT_TOKEN}"
    labels:
      - "traefik.http.routers.reverse.rule=PathPrefix(`/api`)||PathPrefix(`/dashboard`)"
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/var/log/traefik
      - ./certs:/etc/certs
      - ./config/traefik.toml:/etc/traefik/traefik.toml
      - ./config/traefik.config.toml:/etc/traefik/traefik.config.toml

  pgsql:
    image: postgres:13
    container_name: pgsql
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PWD}
    ports:
      - 5432:5432
    volumes:
      - pgsql:/var/lib/postgresql/data
    networks:
      - pgsql
